apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: falcos.falco.org
spec:
  group: falco.org
  names:
    kind: Falco
    listKind: FalcoList
    plural: falcos
    singular: falco
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: falco-operator
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: falco-operator
subjects:
- kind: ServiceAccount
  name: falco-operator
  # Replace this with the namespace the operator is deployed in.
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: falco-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: falco-operator
  template:
    metadata:
      labels:
        name: falco-operator
    spec:
      serviceAccountName: falco-operator
      containers:
        - name: falco-operator
          # Replace this with the built image name
          image: docker.io/falcosecurity/falco-operator:helm-0.5.6
          ports:
          - containerPort: 60000
            name: metrics
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "falco-operator"
