apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: falcorules.mumoshu.github.io
spec:
  group: mumoshu.github.io
  names:
    kind: FalcoRule
    listKind: FalcoRuleList
    plural: falcorules
    singular: falcorule
  scope: Namespaced
  version: v1alpha1
