apiVersion: apps/v1
kind: Deployment
metadata:
  name: falco-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: falco-operator
  template:
    metadata:
      labels:
        name: falco-operator
    spec:
      serviceAccountName: falco-operator
      containers:
        - name: falco-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          ports:
          - containerPort: 60000
            name: metrics
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "falco-operator"
